vim.g.mapleader = " "
vim.keymap.set("n", "<leader>fs", vim.cmd.w)
vim.keymap.set("n", "<leader>bk", function () vim.cmd("q!")end)
vim.keymap.set("n", "<leader>wv", function () vim.cmd("vsplit")end)
vim.keymap.set("n", "<leader>wq", vim.cmd.wq)
vim.keymap.set("n", "<leader>op", vim.cmd.NvimTreeToggle)
vim.keymap.set("n", "<leader>ox", vim.cmd.Mason)
vim.keymap.set("n", "<leader>oth",function ()
require("nvterm.terminal").toggle "horizontal"end)
vim.keymap.set("n", "<leader>otv",function ()
require("nvterm.terminal").toggle "vertical"end)
vim.keymap.set("n", "<leader>otf",function ()
require("nvterm.terminal").toggle "float"end)
vim.keymap.set('n', "<leader>.",require('telescope.builtin').find_files, {})
vim.keymap.set('n', "<leader>ht",require('telescope.builtin').colorscheme, {})
vim.keymap.set('n', "<leader>/",require('telescope.builtin').current_buffer_fuzzy_find, {})
vim.keymap.set('n', "<leader><leader>",vim.cmd.Telescope)
